version: "3.0"

services:

  api:
    build:
      context: ./api
    container_name: api
    volumes:
      - ./api/code:/code
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend/code/public:/code/public
      - ./frontend/code/src:/code/src
      - ./frontend/code/package.json:/code/package.json
      - ./frontend/code/package-lock.json:/code/package-lock.json
    ports:
      - "3000:3000"
    depends_on:
      - api